version: '3'

services:
  web:
    container_name: ci-cd-test-php-apache
    build: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./php-apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    restart: always
    working_dir: /var/www/html

  db:
    container_name: ci-cd-test-mysql
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      TZ: 'Asia/Tokyo'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci-cd-test-phpmyadmin
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${DB_USER_NAME}
      - PMA_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - /sessions